

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
  labels:
    app: appointment-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-system
  template:
    metadata:
      labels:
        app: appointment-system
    spec:
      containers:
        - name: appointment-container
          image: your-dockerhub-username/appointment-booking:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
