apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
